ignoredBuiltDependencies:
  - '@reown/appkit'
  - '@tailwindcss/oxide'
  - bigint-buffer
  - bufferutil
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
